# Generated by Django 5.0.3 on 2024-03-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('nin', models.CharField(max_length=11)),
                ('phone_no', models.CharField(max_length=15)),
                ('vote', models.CharField(max_length=3)),
                ('date_registered', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
